// ============================================================
// Shared Events Data — loaded by events.js AND profile.js
// ============================================================
window.COMUM_EVENTS = [
    {
        id: 1,
        title: 'Sunday Long Ride: Puncak Pass',
        category: 'cycling',
        date: '2026-04-19',
        time: '05:30',
        day: 'Sunday',
        location: 'Comum Hub Sutera',
        locationKey: 'sutera',
        distance: '120 km',
        difficulty: 'hard',
        difficultyLabel: 'Advanced',
        price: 0,
        priceLabel: 'Free',
        attendees: 24,
        capacity: 32,
        image: './Asset/WebP/Cycling_GroupPic_result.webp',
        tags: ['cycling', 'weekend'],
        description: '120km epic ride ke Puncak. SAG support, coffee stops, lunch di atas.',
        featured: true
    },
    {
        id: 2,
        title: 'Padel Night League - Round 4',
        category: 'padel',
        date: '2026-04-17',
        time: '19:00',
        day: 'Friday',
        location: 'Comum Hub Panglima Polim',
        locationKey: 'panglima',
        difficulty: 'medium',
        difficultyLabel: 'Intermediate',
        price: 150000,
        priceLabel: 'Rp 150K',
        attendees: 28,
        capacity: 32,
        image: './Asset/WebP/Padel_Photo1_result.webp',
        tags: ['padel', 'weekend'],
        description: 'Weekly padel tournament. Mixed doubles, best of 3 sets.'
    },
    {
        id: 3,
        title: 'Morning Coffee Ride',
        category: 'cycling',
        date: '2026-04-16',
        time: '06:00',
        day: 'Thursday',
        location: 'Alam Sutera',
        locationKey: 'sutera',
        distance: '35 km',
        difficulty: 'easy',
        difficultyLabel: 'Beginner',
        price: 0,
        priceLabel: 'Free',
        attendees: 18,
        capacity: 25,
        image: './Asset/WebP/Cycliong_GroupPicPoint_result.webp',
        tags: ['cycling', 'beginner'],
        description: 'Easy ride 35km + coffee stop. Perfect for beginners.'
    },

    {
        id: 5,
        title: 'Women Only Padel Clinic',
        category: 'padel',
        date: '2026-04-20',
        time: '09:00',
        day: 'Monday',
        location: 'Comum Hub Sutera',
        locationKey: 'sutera',
        difficulty: 'easy',
        difficultyLabel: 'Beginner',
        price: 200000,
        priceLabel: 'Rp 200K',
        attendees: 8,
        capacity: 12,
        image: './Asset/WebP/Padel_Photo2_result.webp',
        tags: ['padel', 'women', 'beginner'],
        description: 'Clinic khusus perempuan. Dari basics sampai strategy.'
    },
    {
        id: 6,
        title: 'Weekend Warrior Ride',
        category: 'cycling',
        date: '2026-04-18',
        time: '06:00',
        day: 'Saturday',
        location: 'BSD Sentul',
        locationKey: 'outside',
        distance: '80 km',
        difficulty: 'medium',
        difficultyLabel: 'Intermediate',
        price: 0,
        priceLabel: 'Free',
        attendees: 16,
        capacity: 30,
        image: './Asset/WebP/Cycling_GroupPic2_result.webp',
        tags: ['cycling', 'weekend']
    },
    {
        id: 7,
        title: 'Community Coffee & Chat',
        category: 'social',
        date: '2026-04-22',
        time: '18:00',
        day: 'Wednesday',
        location: 'Comum Hub Sutera',
        locationKey: 'sutera',
        difficulty: 'easy',
        difficultyLabel: 'Santai',
        price: 0,
        priceLabel: 'Free',
        attendees: 34,
        capacity: 50,
        image: './Asset/WebP/Cycling_HangoutUndian_result.webp',
        tags: ['social', 'beginner'],
        description: 'Hangout santai, kopi-kopi, cerita-cerita. No agenda.'
    },
    {
        id: 8,
        title: 'Beginner Padel Intro',
        category: 'padel',
        date: '2026-04-21',
        time: '19:30',
        day: 'Tuesday',
        location: 'Comum Hub Alam Sutera',
        locationKey: 'sutera',
        difficulty: 'easy',
        difficultyLabel: 'Beginner',
        price: 100000,
        priceLabel: 'Rp 100K',
        attendees: 10,
        capacity: 16,
        image: './Asset/WebP/Padel_Photo3_result.webp',
        tags: ['padel', 'beginner'],
        description: 'First time di padel? Start here. Racket dan bola disediakan.'
    },
    {
        id: 9,
        title: 'Gravel Adventure Ride',
        category: 'cycling',
        date: '2026-04-25',
        time: '06:30',
        day: 'Saturday',
        location: 'Sentul Loop',
        locationKey: 'outside',
        distance: '60 km',
        difficulty: 'medium',
        difficultyLabel: 'Intermediate',
        price: 50000,
        priceLabel: 'Rp 50K',
        attendees: 14,
        capacity: 20,
        image: './Asset/WebP/Cycling_GroupPic3_result.webp',
        tags: ['cycling', 'weekend']
    },
    {
        id: 10,
        title: 'Padel Doubles Open',
        category: 'padel',
        date: '2026-04-26',
        time: '14:00',
        day: 'Sunday',
        location: 'Comum Hub Panglima Polim',
        locationKey: 'panglima',
        difficulty: 'hard',
        difficultyLabel: 'Advanced',
        price: 250000,
        priceLabel: 'Rp 250K',
        attendees: 30,
        capacity: 32,
        image: './Asset/WebP/Padel_Photo1_result.webp',
        tags: ['padel', 'weekend']
    },
    {
        id: 11,
        title: 'Night Ride CBD Loop',
        category: 'cycling',
        date: '2026-04-24',
        time: '20:00',
        day: 'Friday',
        location: 'Comum Hub Panglima Polim',
        locationKey: 'panglima',
        distance: '25 km',
        difficulty: 'easy',
        difficultyLabel: 'Beginner',
        price: 0,
        priceLabel: 'Free',
        attendees: 20,
        capacity: 35,
        image: './Asset/WebP/speda_one.webp',
        tags: ['cycling', 'beginner']
    },
    {
        id: 12,
        title: 'Hills Hunter Ride',
        category: 'cycling',
        date: '2026-04-23',
        time: '05:30',
        day: 'Thursday',
        location: 'Cimahi Hills',
        locationKey: 'outside',
        distance: '90 km',
        difficulty: 'hard',
        difficultyLabel: 'Advanced',
        price: 0,
        priceLabel: 'Free',
        attendees: 12,
        capacity: 20,
        image: './Asset/WebP/Woman_cycling_result.webp',
        tags: ['cycling']
    }
];

window.COMUM_MONTH_SHORT = ['JAN','FEB','MAR','APR','MAY','JUN','JUL','AUG','SEP','OCT','NOV','DEC'];
window.COMUM_MONTH_NAMES = ['January','February','March','April','May','June','July','August','September','October','November','December'];
